if SERVER then return end

-- load wiki data
require 'DD/gui/wikiData'

-- returns the children of a component
local GetChildren = function (comp)
    local tbl = {}
    for value in comp.GetAllChildren() do
        table.insert(tbl, value)
    end
    return tbl
end

-- set button color
local defaultButtonColor = Color(169, 212, 187)
local setButtonColor = function (button, color)
	button.TextColor = color
	button.HoverTextColor = color
	button.SelectedTextColor = color
	button.Color = color
	button.HoverColor = Color(255, 255, 255)
	button.PressedColor = color
end

-- main frame
local frame = GUI.Frame(GUI.RectTransform(Vector2(1, 1)), nil)
frame.CanBeFocused = false

-- menu frame
local menu = GUI.Frame(GUI.RectTransform(Vector2(1, 1), frame.RectTransform, GUI.Anchor.Center), nil)
menu.CanBeFocused = false
menu.Visible = false

-- put a button that goes behind the menu content, so we can close it when we click outside
local closeButton = GUI.Button(GUI.RectTransform(Vector2(1, 1), menu.RectTransform, GUI.Anchor.Center), "", GUI.Alignment.Center, nil)
closeButton.OnClicked = function ()
	menu.Visible = not menu.Visible
end

-- Make it so the GUI is updated in lobby, game and sub editor
Hook.Patch("Barotrauma.NetLobbyScreen", "AddToGUIUpdateList", function()
    frame.AddToGUIUpdateList()
end, Hook.HookMethodType.After)
Hook.Patch("Barotrauma.GameScreen", "AddToGUIUpdateList", function()
    frame.AddToGUIUpdateList()
end)
Hook.Patch("Barotrauma.SubEditorScreen", "AddToGUIUpdateList", function()
    frame.AddToGUIUpdateList()
end)

-- setup wiki

-- Menu frame and menu list
local menuContent = GUI.Frame(GUI.RectTransform(Vector2(0.57, 0.83), menu.RectTransform, GUI.Anchor.Center))
local menuList = GUI.ListBox(GUI.RectTransform(Vector2(0.95, 0.9), menuContent.RectTransform, GUI.Anchor.Center))

-- label
local text = GUI.TextBlock(GUI.RectTransform(Vector2(1, 0.05), menuContent.RectTransform), "Dam Defense Wiki", nil, nil, GUI.Alignment.Center)
text.CanBeFocused = false
text.textScale = 1.25
	
-- Text
local text = GUI.TextBlock(GUI.RectTransform(Vector2(1, 0.05), menuList.Content.RectTransform), "All Wiki Pages", nil, nil, GUI.Alignment.BottomLeft)
text.CanBeFocused = false

-- Dropdown for selecting prefab
local pageDropdown = GUI.DropDown(GUI.RectTransform(Vector2(1, 0.05), menuList.Content.RectTransform), "-", 3, nil, false)
pageDropdown.ButtonTextColor = Color(169, 212, 187)
for key, value in pairs(DD.wikiData) do
	pageDropdown.AddItem(DD.stringLocalize('wikiName_' .. key) or ('wikiName_' .. key), key)
end

-- page root space : page links space
local k = 0.79

-- Page root (title, body and such)
local pageTitle = GUI.TextBlock(GUI.RectTransform(Vector2(1, 0.05), menuList.Content.RectTransform), '-', nil, nil, GUI.Alignment.Left)
pageTitle.CanBeFocused = false
pageTitle.TextScale = 1.5

local pageRoot = GUI.ListBox(GUI.RectTransform(Vector2(1, 0.75 * k), menuList.Content.RectTransform))
pageRoot.ScrollBarVisible = true
	
local pageBody = GUI.TextBlock(GUI.RectTransform(Vector2(1, 1), pageRoot.Content.RectTransform), '-', nil, nil, GUI.Alignment.TopLeft)
pageBody.CanBeFocused = false
pageBody.Wrap = true

-- Page links (buttons that lead you to related pages)
local text = GUI.TextBlock(GUI.RectTransform(Vector2(1, 0.05), menuList.Content.RectTransform), "Related Pages", nil, nil, GUI.Alignment.BottomLeft)
text.CanBeFocused = false
text.TextScale = 1.5

local pageRelated = GUI.ListBox(GUI.RectTransform(Vector2(1, 0.75 * (1 - k)), menuList.Content.RectTransform))
pageRelated.ScrollBarVisible = true

-- gets the name (title), text (body) and other relevant fields of a wiki page
local getPageFields = function (pageKey)
	local tbl = {
		name = DD.stringLocalize('wikiName_' .. pageKey) or ('wikiName_' .. pageKey),
		text = DD.stringLocalize('wikiText_' .. pageKey) or ('wikiText_' .. pageKey),
	}
	if (pageKey == 'serverMessage') and (Game.IsMultiplayer) then
		tbl.name = Game.ServerSettings.ServerName
		tbl.text = Game.ServerSettings.ServerMessageText
	end
	if (pageKey == 'credits') and File.Exists(DD.path .. '/credits.txt') then
		tbl.text = File.Read(DD.path .. '/credits.txt')
	end
	
	local newline = '    '
	local build = newline
	for count = 1, #tbl.text do
		build = build .. string.sub(tbl.text, count, count)
		if string.sub(build, #build, #build) == '\n' then
			build = build .. newline
		end
	end
	tbl.text = build
	
	return tbl
end

-- Called by "pageDropdown.OnSelected"
DD.loadPage = function (pageKey)
	local pageValue = DD.wikiData[pageKey]
	
	-- change values
	local pageFields = getPageFields(pageKey)
	pageTitle.Text = pageFields.name
	pageBody.Text = pageFields.text
	
	-- link to related pages
	pageRelated.ClearChildren()
	
	-- get amount of related pages (autogenerated pages are not counted)
	if pageValue.related == nil then return end
	local validRelated = {}
	for related in pageValue.related do
		if (DD.wikiData[related] == nil) or (DD.wikiData[related].info == nil) or (not DD.wikiData[related].info.hiddenInGame) then
			table.insert(validRelated, related)
		end
	end
	if #validRelated == 0 then return end
	
	local count = 1
	local itemsPerRow = 4
	for rowIndex = 1, math.ceil(#validRelated / itemsPerRow) do
		local pageRow = GUI.LayoutGroup(GUI.RectTransform(Vector2(1, 0.15 / 0.75 / (1 - k) * 0.2625), pageRelated.Content.RectTransform), nil)
		pageRow.isHorizontal = true
		local items = DD.arrSub(validRelated, count, count + itemsPerRow - 1)
		count = count + itemsPerRow
		for value in items do
			if (DD.wikiData[value] == nil) or (DD.wikiData[value].info == nil) or (not DD.wikiData[value].info.hiddenInGame) then
				local button = GUI.Button(GUI.RectTransform(Vector2(1 / 4, 0.05), pageRow.RectTransform), DD.stringLocalize('wikiName_' .. value), GUI.Alignment.Center, "GUITextBox")
				if DD.tableHas(pageValue.parents, value) then
					setButtonColor(button, Color.Lerp(defaultButtonColor, Color.White, 0.65))
				end
				if value == 'openhtml' then		
					button.OnClicked = function ()
						DD.openHTML(true)
					end
					setButtonColor(button, Color.Lerp(Color(123, 104, 238), Color.White, 0.65))
				else
					button.OnClicked = function ()
						DD.loadPage(value)
					end
				end
			end
		end
	end
end
-- Adds function to pageDropdown onSelect
pageDropdown.OnSelected = function (guiComponent, object)
	DD.loadPage(object)
end
-- Open "main" page
pageDropdown.SelectItem('main')

-- inside close button
local closeButton = GUI.Button(GUI.RectTransform(Vector2(1, 0.05), menuList.Content.RectTransform), "Close Wiki", GUI.Alignment.Center, "GUIButton")
closeButton.OnClicked = function ()
	menu.Visible = not menu.Visible
end

-- Show button to open menu
Hook.Patch("Barotrauma.GUI", "TogglePauseMenu", {}, function ()
    if GUI.GUI.PauseMenuOpen then
		menu.Visible = false
        local frame = GUI.GUI.PauseMenu
        local list = GetChildren(GetChildren(frame)[2])[1]
		local button = GUI.Button(GUI.RectTransform(Vector2(1, 0.1), list.RectTransform), 'DD Wiki', GUI.Alignment.Center, "GUIButton")
		button.OnClicked = function ()
			GUI.GUI.TogglePauseMenu()
			menu.Visible = true
		end
	end
end, Hook.HookMethodType.After)

-- Override server message button to open wiki
if Game.NetLobbyScreen ~= nil then
	local descriptionButton
	for value in Game.NetLobbyScreen.Frame.GetAllChildren() do
		if value.GetType() == GUI.Button and value.Text == 'Description' then
			value.OnClicked = function ()
				menu.Visible = true
				DD.loadPage('serverMessage')
			end
		end
	end
end

-- Generates HTML pages
DD.generateWikiHTML = function ()
	-- guard clauses and retrieve needed file text
	if not File.DirectoryExists(DD.saving.folderPath) then
        File.CreateDirectory(DD.saving.folderPath)
		print('Data folder not found, so one was created at ' .. DD.saving.folderPath)
	end
	local mainPath = DD.path .. '/Lua/DD/gui/main.html'
	local segmentPath = DD.path .. '/Lua/DD/gui/segment.html'
	if not File.Exists(mainPath) then DD.warn('File needed for HTML wiki creation was not found in ' .. mainPath) return end
	if not File.Exists(segmentPath) then DD.warn('File needed for HTML wiki creation was not found in ' .. segmentPath) return end
	local main = File.Read(mainPath)
	local segment = File.Read(segmentPath)
	
	-- anchor
	local anchor = '<a href="#{key}" style="{style}">{text}</a>'
	local sidebar = '<a href="#{key}" style="margin:10px;">{text}</a>'
	local headerInfo = ' <b style="{style}">{text}</b>'
	
	-- adds a wiki entry to the HTML page
	local generatePage = function (key)
		local value = DD.wikiData[key]
		if not value.hidden then
			local tbl = getPageFields(key)
			tbl.class = ''
			-- key (technical)
			tbl.key = key
			-- name
			if DD.wikiData[key].category ~= nil then
				tbl.name = DD.stringReplace('{name} ({category})', {name = tbl.name, category = getPageFields(DD.wikiData[key].category).name})
			end
			-- add info to header (name)
			local nameAppend = ''
			local info = DD.wikiData[key].info or {}
			for key,value in pairs(info) do
				if key == 'main' then
					if value then
						nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = 'Major', style = 'color:tomato;'})
					else
						nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = 'Minor', style = 'color:gold;'})
					end
				elseif key == 'public' then
					if value then
						nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = 'Public', style = 'color:lime;'})
					else
						nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = 'Secret', style = 'color:magenta;'})
					end
				elseif key == 'antagSafe' then
					if value then
						nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = 'Safe', style = 'color:lime;'})
					else
						nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = 'Unsafe', style = 'color:tomato;'})
					end
				elseif key == 'security' then
					if value then
						nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = 'Security', style = 'color:tan;'})
					end
				elseif key == 'proletariat' then
					if value then
						nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = 'Proletariat', style = 'color:lightsteelblue;'})
					end
				elseif key == 'medical' then
					if value then
						nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = 'Medical', style = 'color:salmon;'})
					end
				elseif key == 'nexshopCost' then
					if value then
						nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = value .. ' Credits', style = 'color:cyan;'})
					end
				elseif key == 'nukieshopCost' then
					if value then
						nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = value .. ' Credits', style = 'color:orange;'})
					end
				end
			end
			if info.isAutogen then
				nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = 'Autogenerated', style = 'color:limegreen;'})
				tbl.class = tbl.class .. 'autogen '
			end
			if info.isOverride then
				nameAppend = nameAppend .. DD.stringReplace(headerInfo, {text = 'Overriden', style = 'color:mediumorchid;'})
				tbl.class = tbl.class .. 'override '
			end
			tbl.name = tbl.name .. nameAppend
			-- style for name (header/title)
			tbl.nameStyle = ''
			if (DD.wikiData[key].category ~= nil) and (DD.wikiData[DD.wikiData[key].category].color ~= nil) then
				local color = DD.wikiData[DD.wikiData[key].category].color
				if type(color) == 'userdata' then
					color = DD.colorToHex(color)
				end
				tbl.nameStyle = 'background-color:' .. color .. ';'
			end
			if string.lower(string.sub(key, #key - 2, #key)) == 'job' then
				local job = string.sub(key, 1, #key - 3)
				tbl.nameStyle = 'background-color:' .. DD.colorToHex(Color.Lerp(JobPrefab.Get(job).UIColor, Color.Black, 0.3)) .. ';'
			end
			-- text (wiki entry body)
			tbl.text = '&nbsp;&nbsp;' .. string.gsub(tbl.text, '\n', '<br>&nbsp;&nbsp;')
			-- related (links)
			tbl.related = ''
			local joinString = ' '
			for related in value.related do
				if related ~= 'openhtml' then
					local style = 'margin:0px 3px;'
					if DD.tableHas(value.parents, related) then
						style = style .. "color:black;background-color:mediumslateblue;padding:1px;"
					end
					tbl.related = tbl.related .. DD.stringReplace(anchor, {key = related, style = style, text = getPageFields(related).name}) .. joinString
				end
			end
			tbl.related = string.sub(tbl.related, 1, #tbl.related - #joinString)
			-- prepare for next wiki entry
			tbl.segment = '{segment}'
			-- sidebar
			tbl.class = string.sub(tbl.class, 1, #tbl.class - 1)
			local sidebarTbl =  {key = key, text = getPageFields(key).name}
			local sidebarText = DD.stringReplace(sidebar, sidebarTbl)
			local sidebarStyle = ''
			if info.isAutogen then
				sidebarText = sidebarText .. '<b style="color:limegreen;">•</b>'
			end
			if info.isOverride then
				sidebarText = sidebarText .. '<b style="color:mediumorchid;">•</b>'
			end
			if DD.wikiData[key].category ~= nil then
				sidebarText = '&nbsp;&nbsp;↪' .. sidebarText
			end
			sidebarText = DD.stringReplace('<div id={id} class="{class}" style="{style}">{text}<br></div>', {id = 'sidebar_' .. string.gsub(string.lower(getPageFields(key).name), ' ', '_'), text = sidebarText, class = tbl.class, style = sidebarStyle}) .. '{sidebar}'
			-- apply
			local text = string.gsub(DD.stringReplace(segment, tbl), '%%', '%%%%')
			main = string.gsub(main, '{sidebar}', sidebarText)
			main = string.gsub(main, '{segment}', text)
		end
	end
	
	-- discord invite
	main = string.gsub(main, '{discordInvite}', DD.discordInvite)
	-- main wiki entry has a custom implementation
	main = string.gsub(main, '{mainText}', '&nbsp;&nbsp;' .. string.gsub(getPageFields('main').text, '\n', '<br>&nbsp;&nbsp;'))
	local mainRelated = ''
	for related in DD.wikiData.main.related do
		if related ~= 'openhtml' then
			mainRelated = mainRelated .. DD.stringReplace(anchor, {key = related, style = '', text = getPageFields(related).name}) .. ' | '
		end
	end
	mainRelated = string.sub(mainRelated, 1 , #mainRelated - 3)
	main = string.gsub(main, '{mainRelated}', mainRelated)
	-- order wiki entries
	local tbl = {}
	for key, value in pairs(DD.wikiData) do
		if value.isCategory then
			tbl[key] = {key}
		elseif type(value.parents) == 'table' then
			local chosenParent
			for parent in value.parents do
				chosenParent = parent
			end
			if (chosenParent ~= nil) and (chosenParent ~= 'main') then
				table.insert(tbl[chosenParent], key)
				DD.wikiData[key].category = chosenParent
			end
		end
	end
	-- generate wiki entries
	for category, subtbl in pairs(tbl) do
		for item in subtbl do
			generatePage(item)
		end
	end
	-- final
	main = string.gsub(main, '{segment}', '')
	main = string.gsub(main, '{sidebar}', '')
	File.Write(DD.saving.folderPath .. 'main.html', main)
	return DD.saving.folderPath .. 'main.html'
end